# Generated by Django 4.0.2 on 2022-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=500)),
                ('example', models.CharField(max_length=500)),
            ],
        ),
    ]
