# Generated by Django 4.0.2 on 2022-04-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=100)),
                ('antonym', models.CharField(max_length=100)),
                ('slang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.slang')),
            ],
        ),
    ]
