# Generated by Django 4.0.2 on 2022-04-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_thesaurus'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='slang',
            name='reactions',
            field=models.ManyToManyField(to='main_app.React'),
        ),
    ]
